# Generated by Django 5.2.1 on 2025-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='language',
            field=models.CharField(default='eng', max_length=10),
        ),
    ]
