# Generated by Django 5.2.1 on 2025-05-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='path',
        ),
    ]
