# Generated by Django 5.2.1 on 2025-05-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_remove_docs_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='docs_id',
            new_name='doc',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userstodocs',
            old_name='docs_id',
            new_name='doc',
        ),
    ]
