# Generated by Django 5.2.1 on 2025-05-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_rename_docs_id_cart_doc_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docs',
            new_name='Doc',
        ),
        migrations.RenameModel(
            old_name='UsersToDocs',
            new_name='UserToDoc',
        ),
    ]
